### ISSUE TITLE
复制  剪切等操作可以吗？

### ISSUE THREAD

**Issue by wwdn** [seven332/UniFile#2]
比如文件的复制、剪切等操作可以吗？用什么方法呢？我想从一个文件夹复制到另外一个地方，或者从otgU盘复制到本地等等，可以支持吗？怎么实现呢？

**Comment by seven332** [comment]
复制的话，直接将源文件中的所有内容写入目标文件。若是要剪切，还需删除源文件。

**Comment by wwdn** [comment]
谢谢  已经看到读写流的方法了
